name: React Native CI

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # Cancel current builds if there's a newer commit on the same branch
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install yarn
        run: npm i yarn@1 -g

      - name: Install deps via Yarn
        run: yarn install && yarn graphql-codegen:install && yarn ds:install && yarn graphql-codegen

      - name: Create env
        run: touch .env

      - name: Copy config
        run: mv src/config/defaultDebug.ts src/config/debug.ts

      - name: Check for frozen lockfile
        run: yarn check-lockfile

      - name: Audit CI
        run: yarn audit-ci --config audit-ci.jsonc

      - name: Patch Packages
        run: yarn patch-package

      # - name: Lint
      #   run: yarn format:check && yarn lint:ts && yarn lint:js --quiet

      - name: Unit tests
        run: yarn test
